project:
  type: website
  output-dir: docs

website:
  title: "Matthew J. Weldy"
  description: "Ecology | Analytics | Wildlife | Geospatial"
  site-url: https://yourusername.github.io/website
  repo-url: https://github.com/yourusername/website
  
  navbar:
    logo: /images/logo.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Research"
        href: research.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "CV"
        href: cv.qmd
    right:
      - icon: github
        href: https://github.com/yourusername
      - icon: envelope
        href: mailto:MatthewJWeldy@gmail.com

  sidebar:
    style: "docked"
    search: true

  page-footer:
    left: "© 2025 Matthew J. Weldy"
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    toc-location: right
    code-fold: true
    code-tools: true
    smooth-scroll: true
    link-external-newwindow: true

execute:
  freeze: auto